### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'process_document')

### ISSUE THREAD

**Issue by marquezjorge** [veryfi/veryfi-nodejs#29]
I  followed [this](https://youtu.be/PcJdgnvyfBc) tutorial, when I test it I get the following error:

let response = async() => await my_client.process_document("groceryreceipt.jpg");
                                          ^
TypeError: Cannot read properties of undefined (reading 'process_document')
    at response (/Users/jorge/seniorProject/veryfi/main.js:12:43)
    at Object.<anonymous> (/Users/jorge/seniorProject/veryfi/main.js:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.4.0

Not sure what my issue is, my code is identical to that of the video as well.

**Comment by marquezjorge** [comment]
Found a solution to my problem,  a simple typo... unfortunately i was not able to use this library regardless.
