### ISSUE TITLE
Input should be a valid boolean, unable to interpret input.

### ISSUE THREAD

**Issue by xonaman** [veryfi/veryfi-nodejs#48]
Hello,

looks like we found a bug in the SDK. If the error here is on us, please let us know what we are doing wrong.

```
Error: Error: 400 {"status":"fail","error":"Malformed parameters","details":[{"type":"bool_parsing","loc":["auto_delete"],"msg":"Input should be a valid boolean, unable to interpret input"}]}
    at Client._request (/home/ec2-user/node_modules/@veryfi/veryfi-sdk/lib/client/request.js:56:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.process_document_from_stream (/home/ec2-user/node_modules/@veryfi/veryfi-sdk/lib/documents/processDocumentStream.js:31:20)
    at async process (/home/ec2-user/lib/veryfi.js:51:12)
    at async Object.processReceipt (/home/ec2-user/lib/veryfi.js:76:15)
    at async processReceipt (/home/ec2-user/internal/s3Trigger/handlers/userStorage.js:55:9)
    at async Promise.all (index 2)
    at async Object.receiptUploadHandler (/home/ec2-user/internal/s3Trigger/handlers/userStorage.js:45:9)
    at async default_1 (/home/ec2-user/internal/s3Trigger/index.js:26:17)
    at async /home/ec2-user/internal/index.js:87:13
```

The error claims that the param `auto_delete` was not a valid boolean, but this seems false. This is our code:

```ts
import Veryfi from '@veryfi/veryfi-sdk';
import { VeryfiDocument } from '@veryfi/veryfi-sdk/lib/types/VeryfiDocument';
import { VeryfiExtraArgs } from '@veryfi/veryfi-sdk/lib/types/VeryfiExtraArgs';

export interface ExtractOptions extends VeryfiExtraArgs {
  delete_after_processing: boolean;
}

const client = lib.loadSecrets({
  secret: 'VERYFI_SECRET',
  credentials: 'VERYFI_CREDENTIALS',
}).then(secrets => {
  const credentials = JSON.parse(secrets.credentials);
  return new Veryfi(credentials.clientId, secrets.secret, credentials.userName, credentials.apiKey);
});

export async function process(fileName: string, buffer: Buffer, options: ExtractOptions): Promise<VeryfiDocument> {
  const temp = path.join(os.tmpdir(), path.basename(fileName));
  fs.writeFileSync(temp, buffer);
  const deleteAfterProcessing = options.delete_after_processing;
  delete (options as any).delete_after_processing;
  return await (await client).process_document(temp, [], deleteAfterProcessing, options);
}
```

Thank you very much in advance!

**Comment by alejouribesanchez** [comment]
I've just tested this line of code and for me it is working well

`let response: VeryfiDocument = await veryfi_client.process_document('resources/receipt.png', null, false);` Try removing your options parameter as it seems to be not necessary in your code
